# Generated by Django 3.2.6 on 2021-09-13 23:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='datetimepicker1',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 13, 23, 33, 18, 434123, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predresults',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 9, 13, 23, 33, 46, 881707, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
