# Generated by Django 3.2.6 on 2021-09-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20210913_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='datetimepicker1',
        ),
        migrations.RemoveField(
            model_name='predresults',
            name='timestamp',
        ),
    ]
