# Generated by Django 3.2.6 on 2021-09-14 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_auto_20210914_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='datetimepicker1',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 9, 14, 7, 10, 51, 386525, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predresults',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 9, 14, 7, 10, 56, 804934, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
