# Generated by Django 3.2.6 on 2021-09-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_auto_20210914_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='exeint',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predresults',
            name='namemeals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='datetimepicker1',
            field=models.DateField(blank=True, verbose_name='Date [mm/dd/2020]'),
        ),
    ]
